let M,allScenes=[],visibleScenes=[],i=0,H={},J={},P=JSON.parse(localStorage.getItem("icet_v012")||localStorage.getItem("icet_v011")||localStorage.getItem("icet_v010")||localStorage.getItem("icet_v09")||localStorage.getItem("icet_v08")||localStorage.getItem("icet_v07")||"{}"),currentCat="all";const $=x=>document.getElementById(x),ck=(s,t,c)=>`${s}:${t}:${c}`,jk=(s,t)=>`${s}:${t}`;
const S=()=>visibleScenes[i];
function sp(t,r=.92){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=r;speechSynthesis.speak(u)}
function isFavorite(id){return !!P[id]}
function other(t){let e=document.createElement("div");e.className="turn other";e.innerHTML=`<div class="turnHead"><b>${t.speaker}</b><button>🔊</button></div><div class="en">${t.en}</div><div class="ja">${t.ja}</div>`;e.querySelector("button").onclick=()=>sp(t.en,.9);return e}
function you(s,t,n){let e=document.createElement("div");e.className="turn you";e.innerHTML=`<div class="turnHead"><b>You</b><button class="full">🔊 全文</button></div>`;e.querySelector(".full").onclick=()=>sp(t.en,.88);let m=document.createElement("div");m.className="meaning"+(J[jk(s.id,n)]?" off":"");m.textContent=t.meaning_ja;m.onclick=()=>{J[jk(s.id,n)]=!J[jk(s.id,n)];render()};e.appendChild(m);let g=document.createElement("div");g.className="chunks";t.chunks.forEach((c,j)=>{let q=ck(s.id,n,j),x=document.createElement("div");x.className="chunk"+(H[q]?" off":"");x.innerHTML=`<div class="ce">${c.en}</div><div class="cj">${c.ja}</div><button class="ca">🔊</button>`;x.onclick=()=>{H[q]=!H[q];render()};x.querySelector(".ca").onclick=ev=>{ev.stopPropagation();sp(c.en,.86)};g.appendChild(x)});e.appendChild(g);return e}
function getCategoryCounts(){const counts={all:allScenes.length,favorites:allScenes.filter(s=>isFavorite(s.id)).length};allScenes.forEach(s=>counts[s.category_ja]=(counts[s.category_ja]||0)+1);return counts}
function renderCategoryButtons(){const box=$("cats");box.innerHTML="";const counts=getCategoryCounts();const preferred=["機内","入国","移動","ホテル","学会","食事"];
const present=Array.from(new Set(allScenes.map(s=>s.category_ja)));
const extras=present.filter(c=>!preferred.includes(c));
const order=["all","favorites",...preferred.filter(c=>present.includes(c)),...extras];const labels={all:"すべて",favorites:"お気に入り"};order.forEach(cat=>{const b=document.createElement("button");b.textContent=`${labels[cat]||cat} (${counts[cat]||0})`;if(cat===currentCat)b.className="active";b.onclick=()=>setCategory(cat);box.appendChild(b)})}
function getScenesForCategory(cat){if(cat==="all")return allScenes;if(cat==="favorites")return allScenes.filter(s=>isFavorite(s.id));return allScenes.filter(s=>s.category_ja===cat)}
function setCategory(cat, preserveSceneId=null){currentCat=cat;visibleScenes=getScenesForCategory(cat);if(visibleScenes.length===0){buildSceneSelect();$("count").textContent=`0/0 Scene（全${allScenes.length}件）`;$("dlg").innerHTML='<div class="guide" style="margin-top:10px">お気に入りに登録したSceneはまだありません。</div>';$("cat").textContent='';$("title").textContent='';$("sub").textContent='';$("sit").textContent='';$("tip").textContent='';renderCategoryButtons();return}
  buildSceneSelect();
  if(preserveSceneId){const idx=visibleScenes.findIndex(s=>s.id===preserveSceneId);i=idx>=0?idx:0}else{i=0}
  render();scrollTo({top:0,behavior:"smooth"})}
function buildSceneSelect(){const sel=$("scene");sel.innerHTML="";visibleScenes.forEach((s,n)=>{let o=document.createElement("option");o.value=n;o.textContent=`${s.icon} ${s.category_ja}｜${s.title_ja}`;sel.appendChild(o)})}
function render(){if(!visibleScenes.length){renderCategoryButtons();return}let s=S();$("scene").value=i;$("count").textContent=`${i+1}/${visibleScenes.length} Scene（全${allScenes.length}件）`;$("cat").textContent=`${s.icon} ${s.category_ja} / ${s.category}`;$("title").textContent=s.title_ja;$("sub").textContent=s.title_en;$("sit").textContent=s.situation_ja;$("tip").textContent=s.tip_ja;let d=$("dlg");d.innerHTML="";s.dialogue.forEach((t,n)=>d.appendChild(t.role==="you"?you(s,t,n):other(t)));const fav=isFavorite(s.id);$("star").textContent=fav?"★":"☆";$("star").title=fav?"お気に入り解除":"お気に入り登録";$("star").classList.toggle("mastered",fav);renderCategoryButtons()}
function all(v){let s=S();s.dialogue.forEach((t,n)=>{if(t.role==="you")t.chunks.forEach((_,j)=>H[ck(s.id,n,j)]=v)});render()}
$("hideAll").onclick=()=>visibleScenes.length&&all(true);$("showAll").onclick=()=>visibleScenes.length&&all(false);
$("star").onclick=()=>{if(!visibleScenes.length)return;let s=S();P[s.id]=!P[s.id];if(!P[s.id]) delete P[s.id];localStorage.setItem("icet_v012",JSON.stringify(P));const preserve=s.id;if(currentCat==="favorites") setCategory("favorites", preserve); else render()};
$("prev").onclick=()=>{if(!visibleScenes.length)return;i=(i-1+visibleScenes.length)%visibleScenes.length;render();scrollTo({top:0,behavior:"smooth"})};
$("next").onclick=()=>{if(!visibleScenes.length)return;i=(i+1)%visibleScenes.length;render();scrollTo({top:0,behavior:"smooth"})};
$("scene").onchange=e=>{i=+e.target.value;render()};
$("playAll").onclick=async()=>{if(!visibleScenes.length)return;for(let t of S().dialogue){await new Promise(q=>{let u=new SpeechSynthesisUtterance(t.en);u.lang="en-US";u.rate=.9;u.onend=q;u.onerror=q;speechSynthesis.speak(u)})}};
(async()=>{M=await(await fetch("./materials/demo/material.json")).json();allScenes=M.scenes;setCategory("all");if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js")})();